# Generated by Django 3.2.5 on 2021-07-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='geo_json',
            field=models.JSONField(),
        ),
    ]
